web:
  build: .
  ports:
    - 8080:80
  links:
    - mysql
mysql:
  image: mysql
  environment:
   - MYSQL_DATABASE=bookstack
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=bookstack
   - MYSQL_PASSWORD=admin
  ports:
    - 3306:3306
